version: '2'
services:
  db:
    image: postgres:latest
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"